sudo: required

services:
  - docker

language: generic

git:
  depth: false

install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - git checkout $BRANCH
  - git reset $TRAVIS_COMMIT --hard
  - git status
  - docker pull aaubry/yamldotnet

script:
  - docker run -u root -v `pwd`:/build -w /build -it aaubry/yamldotnet ./build.sh --target Test-Release-Configurations # --verbosity Diagnostic
